name: MyGithubActions
on: 
  push:
    branches: 
      - production
env:
  MY_NAME:  ${{ vars.MY_NAME }}
  MY_STATUS:  ${{ vars.MY_STATUS }}


jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run echo and execute python script
        run: |
          echo "Hello WORLD $MY_NAME"
          python ooo.py  ooo $MY_NAME $MY_STATUS
  my_testing2:
    runs-on: ubuntu-latest
<<<<<<< HEAD

=======
    needs: [my_testing]
>>>>>>> 5cd3c58d9c04d6263e559cea115a88a44a248a6b
    steps:
      - uses: actions/checkout@v1
      - name: Run echo and execute python script
        run: |
          echo "My name is $MY_NAME  im the most powerfull $MY_STATUS"
          python ooo.py  another_function

  
